### ISSUE TITLE
pip install vamp fails on Ventura 13.4.1 (c)

### ISSUE THREAD

**Issue by nite4inspired** [c4dm/vampy-host#7]
`Collecting vamp
  Using cached vamp-1.1.0.tar.gz (107 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/z_/48g009w50_l2scs2k9tbwqxh0000gn/T/pip-build-env-916oxgfd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/z_/48g009w50_l2scs2k9tbwqxh0000gn/T/pip-build-env-916oxgfd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/z_/48g009w50_l2scs2k9tbwqxh0000gn/T/pip-build-env-916oxgfd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/z_/48g009w50_l2scs2k9tbwqxh0000gn/T/pip-build-env-916oxgfd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.`

**Comment by dinizgab** [comment]
Same error here with ubuntu 22.04

**Comment by cannam** [comment]
I'm not sufficiently embedded in the python packaging world to know what the cause is offhand, but it seems very unfortunate for pip/pypi to break long-standing packages like this.

If I can find some time to look into it I will, but this is no longer something I actively work on, so it would mean a cold start and I'm not sure when I will be able to do that.

So I really encourage anyone who recognises the issue to offer a fix or PR - I can also add other maintainers to pypi if someone (with a recognisable trustworthy track record) offers to update it.

Alternatively I can surely make the time if paid to do so, though I realise that's an unlikely scenario given the academic nature of the work.

**Comment by dinizgab** [comment]
Yes, what i found strange was that using only ubuntu runner here in gh actions it doesn't work, for running in a workflow i needed to run in a container.

**Comment by Vuizur** [comment]
For me this [stackoverflow solution](https://stackoverflow.com/a/68038058/5195209) starts compiling the wheel. It involves only creating pyproject.toml with two lines of code, so it's worth trying.

I couldn't compile it unfortunately on Windows, it complained that ssize_t is an undeclared identifier. I think the reason might be that ssize_t might not be supported by the newest MSVC C++ compiler, like somebody mentioned in this issue: https://github.com/eridur-de/mightyscape-1.2/issues/131
